version: '3'
services:
  post-service: 
    build: 
      dockerfile: Dockerfile
      context: ./post
      args:
        NODE_ENV: dev
    volumes:
      - ./:/app
      - /app/post/node_modules
    env_file:
      - ./post/.env.dev
    command: npm run dev

  # post-service1: 
  #   build: 
  #     dockerfile: Dockerfile
  #     context: ./post
  #     args:
  #       NODE_ENV: dev
  #   volumes:
  #     - ./:/app
  #     - /app/post/node_modules
  #   env_file:
  #     - ./post/.env.dev
  #   command: npm run dev
    